apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: default
type: Opaque
stringData:
  POSTGRES_DB: statustracker
  POSTGRES_USER: appuser
  POSTGRES_PASSWORD: changeme 
  DATABASE_URL: postgresql://appuser:changeme@db:5432/statustracke

